import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ProfileImage from "src/public/IMG_5794.jpg";
import AvaterImage from "src/public/ReadyPlayerMe-Avatar (1).png";
import Footer from "src/components/Footer";
import { BsGithub, BsTwitter, BsInstagram } from "react-icons/bs";
import HeaderResponsive from "src/components/Header";
import { SocalMedia } from "src/components/Socialmedia";
import { MyProfile } from "src/components/MyProfile";

const Home: NextPage = () => {
	return (
		<div className="px-2">
			<Head>
				<title>Naoki Hayahsida</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HeaderResponsive
				links={[
					{
						link: "/",
						label: "Home",
					},
					{
						link: "/blog",
						label: "Blog",
					},
				]}
			/>
			<div className="flex flex-1 flex-col min-h-screen items-center justify-center">
				<MyProfile />

				<SocalMedia />
			</div>
			<Footer />
		</div>
	);
};
export default Home;
