import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ProfileImage from "src/public/IMG_5794.jpg";
import Footer from "src/components/Footer";
import { BsGithub, BsTwitter, BsInstagram } from "react-icons/bs";
import Link from "next/link";
import HeaderResponsive from "src/components/Header";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HeaderResponsive
				links={[
					{
						link: "/about",
						label: "About",
					},
					{
						link: "/projects",
						label: "Projects",
					},
				]}
			/>
			<div className="flex flex-col items-center justify-center pt-12">
				<div>
					<Image
						alt="ProfileImage"
						layout="intrinsic"
						src={ProfileImage}
						width={250}
						height={250}
						className="rounded-full object-cover object-top"
					/>
					<h1 className="text-4xl font-bold text-center pt-12">
						Naoki Hayashida
					</h1>
				</div>

				<div className="pt-12 flex space-x-10">
					<Link href="https://github.com/Naoki0509">
						<a>
							<BsGithub className="text-6xl" />
						</a>
					</Link>
					<Link href="https://twitter.com/nakki0509">
						<a>
							<BsTwitter className="text-6xl" />
						</a>
					</Link>
					<Link href="https://www.instagram.com/naoking0509">
						<a>
							<BsInstagram className="text-6xl" />
						</a>
					</Link>
				</div>

				<Footer />
			</div>
		</div>
	);
};
export default Home;
